### ISSUE TITLE
Fix and improve definitions, together with a major clean-up

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#1]
Please fix the weird URIs such as ...urigen....
Please fix concepts with more than one definition so that all have exactly one.

Workflow:
-------------
get a token by email when free
..edamontology [master]> git pull
edit EDAM_1.4_dev.owl locally
check up & validate locally
..edamontology [master]> git add EDAM_1.4_dev.owl
..edamontology [master]> git commit
fill in description of the commit
..edamontology [master]> git push origin
release token by email if everything alright

**Comment by matuskalas** [comment]
Perhaps the `xml:lang` attribute could be useful to have at the level of labels and definitions, for openness towards both _e.g._ エダム or even GB|US|*etc.* kinds of eventual future developments.

And useful for crawlers, search optimisation, automated data extraction, ...

**Comment by joncison** [comment]
There are too many different strands to this issue: @matuskalas please close it and create individual, more actionable issues instead.

**Comment by joncison** [comment]
@matuskalas 

This issue is not actionable yet, so I'm closing it.  

I've added all the items (which are to do with validations) to our internal tracker:
https://docs.google.com/spreadsheets/d/1qjh9DEkOAxJxMHghOX2rSYJutpTwPuIG961oyS363l8/edit#gid=1823636494

In due course they can be moved to here:
https://github.com/edamontology/edamxpathvalidator
