### ISSUE TITLE
Preferred label also exact synonym

### ISSUE THREAD

**Issue by krdav** [edamontology/edamontology#130]
Some concepts have an exact synonym which is the same as its preferred name. In some cases the exact synonym is just a lower/upper case of the preferred label.

In the following list of concepts this probelm occoured:
mmcif
rna-seq alignment
id retrieval
svg
rna-seq
png
hgmd id
isa-tab
gi number
dna-seq
cosmic id
polymorphism detection

**Comment by hmenager** [comment]
many of these synonyms are just a change in case. e.g.:
COSMIC ID hasExactSynonym cosmic id.
@joncison , what should we do with these? IMHO, probably retaining only the official case would be the best option, and ensuring tooling enables case-insensitive searches for terms.

**Comment by joncison** [comment]
+1

otherwise EDAM will degenerate quite badly

thee same can be said for english / american spellings

**Comment by joncison** [comment]
OK - all these fixed in EDAM_1.15.  I also added a note to HOW_TO_EDIT.md 

"NB: Do **not** include American spellings or case variants as synonyms"

**Comment by bug1303** [comment]
This has been closed as 'fixed in EDAM_1.15', however in 1.16, there still are plenty of cases (may of them reported before) where the same term is used as preferred label and synonym (or two synonyms), only differing in case:

data_1104 : UniGene cluster ID
data_2314 : gi number
data_3264 : cosmic ID
data_3264 : cosmic identifier
data_3265 : hgmd ID
data_3265 : HGMD identifier
format_1477 : mmcif
format_3603 : png
format_3604 : svg
format_3687 : ISA-Tab
format_3748 : Linked Data format
topic_3170 : RNA-seq
topic_3170 : Small RNA-Seq
topic_3179 : ChIP-chip
operation_3289 : id retrieval
operation_3289 : Data retrieval (id)
operation_3202 : Polymorphism detection

**Comment by matuskalas** [comment]
The reported cases will be fixed, and after edamontology/edamxpathvalidator#3 is added, additional such cases need to be fixed, too.

**Comment by joncison** [comment]
all now done (which were all case variants)
