### ISSUE TITLE
Missing "OTU table"

### ISSUE THREAD

**Issue by mlangill** [edamontology/edamontology#148]

**Comment by joncison** [comment]
Added in EDAM_1.15:
BIOM table
http://edamontology.org/data_3740

with "OTU table" as narrowSynonym

**Comment by matuskalas** [comment]
This clearly sounds like nonsense, because

- __BIOM__ is a specific __Format__
- __BIOM table__ is an OOP library object (thus either not a concern of EDAM, or an incarnation of __BIOM__ as a __Format__)
- __OTU table__ is a type of __Data__

**Comment by matuskalas** [comment]
_**BIOM format**_ (http://edamontology.org/format_3746) added instead into the development version towards release 1.15 (See #172). It is a format of a _**Biodiversity report**_ (http://edamontology.org/data_3707). The latter should be used when annotating "OTU tables" or "BIOM tables" as types of data. In more specific cases, _**Alpha**_, _**Beta**_, or _**Gamma diversity data**_ can be used (http://edamontology.org/data_3737, http://edamontology.org/data_3738, http://edamontology.org/data_3739, corrected in f886147c975315f2345b12963a839d97264e15d2). _**OTU table**_ has been added as a narrow synonym to a _**Biodiversity report**_ (fixed in f63a7db71fabb1b58fadd3d1a1fc28edb60513c0).
