### ISSUE TITLE
Hack git: Store released versions of EDAM in GitHub as successive revisions

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#177]
Ideally all historical versions (_e.g._ from [NCBO BioPortal](https://bioportal.bioontology.org/ontologies/EDAM)).

Would be **much more useful** for seeing differences than Bubastis.

Plus add how to this into the **_Release recipe_**.

**Comment by hmenager** [comment]
This could be done if we had migrated the previous cvs based history to git in a canonical way, but unfortunately we did not. Since all the recent ones are indeed available in git, going through the pain and risks of rewriting the git history would not be worthy. I'm not sure this is what you're asking, though. Is it?

**Comment by joncison** [comment]
I've added all the historic versions to the releases here:
https://github.com/edamontology/edamontology/tree/master/releases

We shouldn't mess with the git history

can I close this?

**Comment by matuskalas** [comment]
Now I really did this.
