### ISSUE TITLE
need for a cleanup in subset of OWL source

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#192]
I do not have the time to elaborate much, but it seems some OWL classes are defined as belonging to the wrong "subset". Take for instance operation_3443, which is in subsets data AND operation.
Following code is a draft that shows how the detection could be automated is a python/xpath way:
https://gist.github.com/hmenager/aa2520e12d7fb1be54ddfdedda28a763
There is however probably a way to define this in OWL as forbidden in a declarative way.

**Comment by joncison** [comment]
thanks!  so this needs to be made part of the CI, a report made, then we do a cleanup

**Comment by joncison** [comment]
That one fixed in EDAM_1.16

This just crept in from the manual edit process; may well be a couple of others lurking.

@hmenager will you please move this issue to https://github.com/edamontology/edamxpathvalidator.   This is def. requires auto-validation.  We should probably rename that repo to include all things validation ?
