### ISSUE TITLE
Operation request: Fragmenation tree generation

### ISSUE THREAD

**Issue by vatsi16** [edamontology/edamontology#346]
For the annotation of https://www.ncbi.nlm.nih.gov/pubmed/19015140

I think it could fit good under "Spectral analysis" - http://edamontology.org/operation_3214 .
Since it's a tree, it can be visualized too, it might fit under "Visualisation" too -http://edamontology.org/operation_0337 .

**Comment by joncison** [comment]
Is this the right reference?  The paper goes on about calculating a sum formula for a metabolite ....

anyhow, pls. check and write back here in clarification, ideally with a definition of the concept.

Thanks!

**Comment by joncison** [comment]
@veitveit  - could you take a look at this one please?  "Fragmentation tree generation" seems a very highly specialised concept, so perhaps a synonym of some existing concept?  Please advise.

**Comment by joncison** [comment]
@veitveit I'm specifying this as _narrowSynonym_ of [Natural product identification](http://edamontology.org/operation_3803) which itself has _broadSynonym_ of _Metbolite identification_

think this is ok ... comment otherwise!

**Comment by veitveit** [comment]
Tricky one. I assume this corresponds to an algorithm/tool that calculates and predicts the fragment ions of a compound after e.g. sending it through a gas.

This is quite unspecific to molecules but mostly related to metabolites, lipids and proteins and might even be an own term under _Calculation_, _Spectra analysis_ and/or _Prediction and recognition_.

I say that because there might come more than that, also with a potential synonym of _fragmentation spectra prediction_ and then move it to _Spectra analysis_

@joncison What do you think?
