### ISSUE TITLE
"PDB Models" format

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#383]
@jlgelpi please help

From https://github.com/edamontology/edamontology/issues/353 the following format is suggested:

PDB models
PDB file with MODELS representing snapshots (structure conformations) of a trajectory or ensemble.
Useful for 3D visualizations being a self-sufficient file with both information about topology and coordinates. Not recommended as a trajectory format, because it is duplicating the topology information in every snapshot, represented as a MODEL in the PDB file.

This is just PDB format right?  Or rather, a constraint of it.  I'm happy to add the concept if it'd be useful for practical purpose - or is just "PDB" format enough?  Please advise.

**Comment by jlgelpi** [comment]
As "format", itt is standard PDB format. It is used, however, to hold a series of structures through the use of MODELS,. It is also to the usual way of presenting experimental structures coming from NMR. The right thing to do is perhaps to state that PDB "is a format" for MD trajectories instead of generating a separate entry. Another option would be a descendent of PDB as "Multiple structure PDB"  to inforce the use of MODELS.

**Comment by joncison** [comment]
thanks

I've added _PDB database entry format_ **is_format_of** _Trajectory data_

Feeling is, we should prob. just leave at that (_i.e._ no _Multiple structure PDB_), as there'll be a lot of devil in the detail of all sorts of formats, which we can't hope to capture in EDAM.

cc @matuskalas
