### ISSUE TITLE
Propose to merge “DNA sequence” and “DNA sequence (raw)"

### ISSUE THREAD

**Issue by albangaignard** [edamontology/edamontology#397]
@jvanheld

**Comment by joncison** [comment]
@albangaignard I'm deprecating all the instances of "raw" sequence data types:

Reason given in the deprecation comment:  _Deprecated because this is bloat / confusing & better handled as an EDAM Format concept - "raw" sequences just imply a particular format (i.e. one with a vanilla string, possible in a particular alphabet, with no metadata)._

These are now deprecated:
http://edamontology.org/data_0848
http://edamontology.org/data_3497
http://edamontology.org/data_2975
http://edamontology.org/data_3496
http://edamontology.org/data_2974

**Comment by albangaignard** [comment]
Ok @joncison, thanks for this clarification, the "raw" term was indeed confusing.
