### ISSUE TITLE
how should links from EDAM pointing out to documentation and example data work?

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#414]
This is asking for expert advice (@albangaignard ?)
We have some links in EDAM to external resources for documentation and example data. Is it fine to have these specified as `rdf:resource`, given the facts that (1) these resources are not RDF resource _per se_, and (2) they are not either identifiers in any way (not stable URLs).
If rdf:resource is not the way to specify this, is there a better formal way to do it. I and @matuskalas would love to get your input on that @albangaignard.

**Comment by albangaignard** [comment]
@hmenager, @matuskalas, `rdf:resource` is a syntax specific to the XML serialization of RDF. 

I would stick to the `RDF Schema` specification. Just using the `rdfs:seeAlso` property would be ok for me : https://www.w3.org/TR/rdf-schema/#ch_seealso. There is no contraints on the format of the designated object. Hope that helps.

**Comment by joncison** [comment]
hi guys

I think we'd need to keep the semantic distinction between such things, so we'd want to subclass an existing annotation property.

See this [thread](https://github.com/edamontology/edamontologyDocs/issues/10) where it was mooted to subclass ``<rdfs:comment>``

**Comment by joncison** [comment]
It would be nice to settle a proposal for this, because we have users e.g. https://github.com/edamontology/edamontology/issues/552 who've diligently specified links to specification and documentation for their data format which, as things stand, will all get lumped together as ``<documentation>``.  Along with links for publication and to Wikpedia.   A bit of a mess.  

See https://github.com/edamontology/edamontologyDocs/issues/10 where we go into requirements for Format concepts in more depth.

cc @hmenager @matuskalas @albangaignard

**Comment by joncison** [comment]
@hmenager @matuskalas @albangaignard I just migrated edamontology/edamontologyDocs#10 to this tracker (issue https://github.com/edamontology/edamontology/issues/579) as per your suggestion Matus.  Let's take the discussion there.  Will close this.
