### ISSUE TITLE
entry for .msf (Magellean Storage file) is missing

### ISSUE THREAD

**Issue by mayerg97** [edamontology/edamontology#59]
ProteomeDiscoverer outpur file format (a SQLite DB)

**Comment by hmenager** [comment]
@mayerg97 , do you have a definition of this format? thank you.

**Comment by joncison** [comment]
@mayerg97, please provide a link to the format spec (or some link where the format is described).  It's mentioned in http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3518119/ and http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4206089/ but I can't find a description of the format anywhere.

**Comment by germa** [comment]
@hmenager, @joncison: The .msf format is a proprietary mass-spectrometry format of Thermo Scientific's ProteomeDiscoverer software, which is very wide-spread in use. In principle it is a SQLite database, and you can look into the files with e.g. SQLiteStudio3. There are also some readers (http://pubs.acs.org/doi/abs/10.1021/pr2005154) and converters (http://www.sciencedirect.com/science/article/pii/S1874391915300531) for this format available, which re-engineered the database schema, but there is no official DB schema specification of Thermo Scientific for that format. It would be good to have that format, so that we can specify it in the ProCon converter software as input format.

**Comment by joncison** [comment]
@mayerg97, in next release:

"MSF" (http://edamontology.org/format_3702) 

... although it's an edge-case because no public format spec exists
