### ISSUE TITLE
Add user output to the pre-commit hook (good for learning basic Bash shell scripting)

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#633]
Please add text output for the user:
- error message if no `owl:Class` found
- success message otherwise (perhaps with how many times `owl:Class` was found)

to the `/.githooks/pre-commit` Bash [script](https://github.com/edamontology/edamontology/blob/main/.githooks/pre-commit).

[A good small task for newcomers, e.g. Outreachy applicants. A good issue to do first before this: #616(setup)]

----

**Learning Bash shell:**
- [Command line essentials for Bioinformaticians](https://bcc2020cle.bioinformatics.guide/) ([Slides here](https://rpubs.com/iracooke/bcc2020cle), [Video here](https://bcc2020.sched.com/event/c7Sz/command-line-essentials-for-bioinformaticians) or on [Vimeo](https://vimeo.com/441683367), Hands-on exercises linked from the first site)
- [Software Carpentry shell tutorial](http://swcarpentry.github.io/shell-novice/)

> **About Git and Git hooks:**
>  - Quick introduction|refresh of [Git and GitHub](https://coderefinery.github.io/git-refresher/02-refresher/) (101)
>  - Install Git: see [here](https://coderefinery.github.io/git-refresher/01-setup) and [here](https://carpentries.github.io/workshop-template/#git)
>  - Install a convenient [text editor](https://coderefinery.github.io/installation/editors/) ([see also](https://carpentries.github.io/workshop-template/#editor))
>  - [Learn Git](https://coderefinery.github.io/git-intro/) (great for both beginners and advanced)
>  - [Forking](https://coderefinery.github.io/git-collaborative/03-distributed/) a GitHub repository and creating a pull request
>  - Git hooks: [quick overview](https://coderefinery.github.io/git-collaborative/05-hooks/)

**Comment by melibleq** [comment]
Hey @matuskalas! I'm Melissa from São Paulo - Brazil. Currently browsing good first issues and their related ones.

I am familiar with git but not with git hooks. As far as I could understand, they somehow work as a tool to automate part of the git workflow. Please correct me if I didn't get it very well.

So, with this issue, you want the contributor to suggest an edition to the [pre-commit script](https://github.com/edamontology/edamontology/blob/main/.githooks/pre-commit)? For instance, adding echo messages?

I have been using Linux (Ubuntu) since March 2020 and that makes this task especially interesting to me. I'd be glad if you could assign it to me.

Please let me know if there are other similar new issues that I could also work on.

Thanks a lot!

**Comment by matuskalas** [comment]
Hey @melibleq 😊
Indeed, I think you understood it exactly right👍🏽

**Comment by AnkitaxPriya** [comment]
May I work on this issue too @matuskalas ?

**Comment by Uttam-Singhh** [comment]
Can I also work on this? @matuskalas

**Comment by matuskalas** [comment]
@AnkitaxPriya or @Uttam-Singhh, do you want to look at a similar (although probably easier) issue #644?

After @melibleq creates a pull request with a solution to this one, others are welcome to improve it further. 🐱‍🚀

**Comment by AnkitaxPriya** [comment]
Sure @matuskalas! 😄

**Comment by Uttam-Singhh** [comment]
Will work on #644!
Thank you! @matuskalas

**Comment by AnkitaxPriya** [comment]
Hello @matuskalas, since nobody worked on this issue, may I work on this? I am interested to contribute.

**Comment by melibleq** [comment]
> Hello @matuskalas, since nobody worked on this issue, may I work on this? I am interested to contribute.

Hi @AnkitaxPriya! I have worked on it [here](https://github.com/edamontology/edamontology/pull/661). Please feel free to review it and add your comments or ideas, if you want to!
