### ISSUE TITLE
Adding the metabarcoding as a sub-topic, possibly as a child of metagenomics

### ISSUE THREAD

**Issue by Woolly-at-EBI** [edamontology/edamontology#856]
**Topic name:**  metabarcoding

**Short description:** Metabarcoding is the barcoding of DNA or RNA to identify multiple taxa from the same sample. Typically high throughput sequencing is performed and the resulting sequence reads matched to a DNA barcode reference database,

**Parent URI(s):** http://edamontology.org/topic_3174

**exactSynonym(s):** 

**narrowSynonym(s):** eDNA Metabarcoding|eRNA Metabarcoding

**Wikipedia:** https://en.wikipedia.org/wiki/Metabarcoding

**Comment:** Thank you.

**Comment by matuskalas** [comment]
Fixed in bde3b8bc0. Will be updated on the NCBO BioPortal and in TeSS within this week. The ID http://edamontology.org/topic_4038 is now permanent.

Giant thanks for creating the issue @Woolly-at-EBI 🙏🏽 I added you with your name and GitHub bogus email as a co-author of the commit. I hope that's alright; please let me know if not.

**Comment by Woolly-at-EBI** [comment]
Thanks Matus for adding this metabarcoding term. I am really pleased that we now get on use this as an EDAM ontological term and id. It helps to improve FAIRness of the metadata and thus data. It think that it is additionally a child of metagenomics, but that is minor.

Yes, happy as a co-author of the commit, such seems like good practice.
