### ISSUE TITLE
[BUG] Invalid literal query string parameter in entrypoint redirect causes not found error

### ISSUE THREAD

**Issue by fmigneault** [edamontology/edamontology#863]
The website entrypoint (https://edamontology.org/) causes a literal redirect to `https://edamontology.org/page%3f` which causes a 404 not found error. The URL code `%3f` stands for `?`. It seems the query parameter delimiter gets encoded somewhere as special URL character. Using either `https://edamontology.org/page` or `https://edamontology.org/page?` directly produces the intended response.

**Comment by matuskalas** [comment]
Million thanks for your detailed description and your fix in https://github.com/crim-ca/weaver/commit/2edb06363b0f74a7dfcc79d7cb444507142a4571 🙏🏽

This bug is unfortunately a known issue since the outcome of the partial quick-fix of #861. We're still working on solving it ☹ I'm marking this issue as `duplicate` of #861.
